# Generated by Django 3.2.7 on 2021-09-25 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210925_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khojthesearch',
            name='input_value',
        ),
        migrations.AddField(
            model_name='khojthesearch',
            name='input_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inputvalues'),
        ),
    ]
