# Generated by Django 3.2.7 on 2021-09-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210925_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khojthesearch',
            name='input_value',
        ),
        migrations.AddField(
            model_name='khojthesearch',
            name='input_value',
            field=models.ManyToManyField(to='core.InputValues'),
        ),
    ]
